runserver:
	java chatserve 1032

runclient:
	./chatclient flip1.engr.oregonstate.edu 1032
 
clean:
	rm -f chatclient
	rm -f chatserve.class

run:
	javac chatserve.java
	gcc -o chatclient chatclient.c
